/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package doan;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class FormHoaDonXuat extends javax.swing.JFrame {
    
     private ArrayList<HoaDonXuat> list;
    DefaultTableModel model;
    /**
     * Creates new form HoaDonNhap
     */
    public FormHoaDonXuat() {
        initComponents();
         list = new DAO().getListHDXuatThuoc();
        model =(DefaultTableModel) dgvHoaDonXuat.getModel();
        HienThi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dgvHoaDonXuat = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\java\\DoAn\\src\\Image\\iconfinder_635_Bill_excel_file_invoice_statement_4017677.png")); // NOI18N
        jLabel1.setText("HÓA ĐƠN XUẤT");

        txtTimKiem.setToolTipText("");
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconfinder_11_Search_106236.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        dgvHoaDonXuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "ID", "Người Bán", "Tên Thuốc", "Loại Thuốc", "Đơn Giá", "Số Lượng", "Ngày Xuất", "Khách Hàng", "Thành Tiền"
            }
        ));
        dgvHoaDonXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dgvHoaDonXuatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dgvHoaDonXuat);
        if (dgvHoaDonXuat.getColumnModel().getColumnCount() > 0) {
            dgvHoaDonXuat.getColumnModel().getColumn(1).setResizable(false);
            dgvHoaDonXuat.getColumnModel().getColumn(7).setResizable(false);
        }

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconfinder_basket_1814090.png"))); // NOI18N
        jButton2.setText("Xóa");

        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconfinder_left_3_4829864.png"))); // NOI18N
        btnQuayLai.setText("Quay Lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconfinder_basket_1814090.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimKiem)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuayLai)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnQuayLai)
                    .addComponent(btnXoa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        new QuanLyHoaDon().setVisible(true);
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void dgvHoaDonXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dgvHoaDonXuatMouseClicked
         btnXoa.setEnabled(true);
       
        
       
    }//GEN-LAST:event_dgvHoaDonXuatMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int xacNhan = JOptionPane.showConfirmDialog(null,"Bạn có muốn xóa không",null,JOptionPane.YES_NO_OPTION);
        if(xacNhan == JOptionPane.YES_OPTION){
            
            
             HoaDonXuat thuoc = new HoaDonXuat();
             int ID = (Integer) model.getValueAt(dgvHoaDonXuat.getSelectedRow(), 1);  
                 thuoc.setID(ID);
                 
              if(new DAO().xoaHDXuatThuoc(thuoc)){
                     JOptionPane.showMessageDialog(rootPane,"Xóa Thành Công");
             
  
                     model.removeRow(dgvHoaDonXuat.getSelectedRow());
                     
        
                 }
                 else{
                     JOptionPane.showMessageDialog(rootPane,"Xóa thất bại !");
                }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
                boolean isKetQua = true;
         
         Vector  row = new Vector();
         int STT =1; 
            while(model.getRowCount() >0)
              {
                  model.removeRow(0);
              }
             
             
             ArrayList<HoaDonXuat> listTimKiem; 
                     
              listTimKiem =new DAO().searchHDXuat(txtTimKiem.getText().toString());
              isKetQua = false;
              if(txtTimKiem.getText().equals("")){
               HienThi();
             }
         
              if(isKetQua == false){
                        
                  
                    for (HoaDonXuat xt : listTimKiem) {
                        
                        row.add(STT);
                        row.add(xt.getID());
                        row.add(xt.getNguoiBan());                      
                        row.add(xt.getTenThuoc());
                        row.add(xt.getLoaiThuoc());
                        row.add(xt.getDonGia());
                        row.add(xt.getSoLuong());
                        row.add(xt.getNgayXuat());
                          row.add(xt.getTenKH());
                        row.add(xt.getThanhTien());
                        model.addRow(row);
                    }
                    STT ++;
                    model.fireTableDataChanged();
                }
              else{
                     row.add(STT);
                        row.add("");
                        row.add("");
                        row.add("");
                        row.add("");
                        row.add("");
                        row.add("");
                        row.add("");
                        row.add("");
                        row.add("");
                        model.fireTableDataChanged();
              }        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimKiemActionPerformed
   public void HienThi(){
         model.setRowCount(0);
        int STT =1;
        for (HoaDonXuat t : list) {
          
            model.addRow(new Object[]{STT,t.getID(),
             t.getNguoiBan(),t.getTenThuoc(),t.getLoaiThuoc(),t.getDonGia(),t.getSoLuong(),t.getNgayXuat(),t.getTenKH(),t.getThanhTien()
            });
            STT ++;
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHoaDonXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHoaDonXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHoaDonXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHoaDonXuat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHoaDonXuat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JTable dgvHoaDonXuat;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
