/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package doan;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class ManHinhChinh extends javax.swing.JFrame {

    /**
     * Creates new form ManHinhChinh
     */
    public ManHinhChinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_QLNhapThuoc = new javax.swing.JButton();
        btn_QLXuat = new javax.swing.JButton();
        btn_QLHoaDon = new javax.swing.JButton();
        btnThongTin = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\java\\DoAn\\src\\Image\\iconfinder_thefreeforty_shop_1243706.png")); // NOI18N
        jLabel1.setText("QUẢN LÝ NHÀ THUỐC");

        btn_QLNhapThuoc.setIcon(new javax.swing.ImageIcon("D:\\java\\DoAn\\src\\Image\\iconfinder_sign-in_54156.png")); // NOI18N
        btn_QLNhapThuoc.setText("Quản Lý Nhập Thuốc");
        btn_QLNhapThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLNhapThuocActionPerformed(evt);
            }
        });

        btn_QLXuat.setText("Quản Lý Xuất Thuốc");
        btn_QLXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLXuatActionPerformed(evt);
            }
        });

        btn_QLHoaDon.setText("Quản Lý Hóa Đơn");
        btn_QLHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLHoaDonActionPerformed(evt);
            }
        });

        btnThongTin.setIcon(new javax.swing.ImageIcon("D:\\java\\DoAn\\src\\Image\\iconfinder_aiga_information_134192.png")); // NOI18N
        btnThongTin.setText("Thông Tin");
        btnThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinActionPerformed(evt);
            }
        });

        btnThoat.setIcon(new javax.swing.ImageIcon("D:\\java\\DoAn\\src\\Image\\iconfinder_log_out_678146.png")); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_QLXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_QLNhapThuoc)
                            .addComponent(btn_QLHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(456, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(89, 89, 89)
                .addComponent(btn_QLNhapThuoc)
                .addGap(50, 50, 50)
                .addComponent(btn_QLXuat)
                .addGap(54, 54, 54)
                .addComponent(btn_QLHoaDon)
                .addGap(77, 77, 77)
                .addComponent(btnThongTin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnThoat)
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_QLNhapThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLNhapThuocActionPerformed
        // TODO add younew r handling code here:
        new QuanLyNhapThuoc().setVisible(true);
    }//GEN-LAST:event_btn_QLNhapThuocActionPerformed

    private void btn_QLXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLXuatActionPerformed
        // TODO add your handling code here:
          new QuanLyXuatThuoc().setVisible(true);
    }//GEN-LAST:event_btn_QLXuatActionPerformed

    private void btn_QLHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLHoaDonActionPerformed
        // TODO add your handling code here:
          new QuanLyHoaDon().setVisible(true);
    }//GEN-LAST:event_btn_QLHoaDonActionPerformed

    private void btnThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinActionPerformed
        // TODO add your handling code here:
          new ThongTin().setVisible(true);
    }//GEN-LAST:event_btnThongTinActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
       int Exit = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không");
       if(Exit == JOptionPane.YES_OPTION){
           System.exit(Exit);
       }
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManHinhChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThongTin;
    private javax.swing.JButton btn_QLHoaDon;
    private javax.swing.JButton btn_QLNhapThuoc;
    private javax.swing.JButton btn_QLXuat;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
