/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package doan;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class QuanLyXuatThuoc extends javax.swing.JFrame {

      private ArrayList<XuatThuoc> list;
    DefaultTableModel model;
    /**
     * Creates new form QuanLyNhapThuoc
     */
    public QuanLyXuatThuoc() {
        initComponents();
        list = new DAO().getListXuatThuoc();
        model =(DefaultTableModel) dgvXuatThuoc.getModel();
        HienThi();
        btnSua.setEnabled(false);
        btnSua.setEnabled(false);
        txtThanhTien.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        spnSoLuong = new javax.swing.JSpinner();
        txt_NguoiBan = new javax.swing.JTextField();
        txt_TenThuoc = new javax.swing.JTextField();
        cbxLoaiThuoc = new javax.swing.JComboBox();
        txt_NgayXuat = new javax.swing.JTextField();
        txtThanhTien = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        dgvXuatThuoc = new javax.swing.JTable();
        txt_TenKH = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_DonGia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setText("Đơn Gía");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\java\\DoAn\\src\\Image\\iconfinder_586_Medicine_pills_tablets_4212198.png")); // NOI18N
        jLabel1.setText("QUẢN LÝ XUẤT THUỐC");

        jLabel2.setText("Người Bán");

        jLabel3.setText("Tên Thuốc");

        jLabel4.setText("Loại Thuốc");

        jLabel5.setText("Số Lượng");

        jLabel8.setText("Ngày Xuất");

        jLabel9.setText("Thành Tiền");

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconfinder_199_CircledPlus_183316.png"))); // NOI18N
        btnThem.setText("Thêm ");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconfinder_basket_1814090.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconfinder_Setting01_928428.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconfinder_back3_216570.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconfinder_11_Search_106236.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconfinder_left_3_4829864.png"))); // NOI18N
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        cbxLoaiThuoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kháng Sinh", "Vỉtamin", "Thuốc giảm đau", "Thuốc giảm cân", "Thuốc cảm cúm", "Thuốc đau họng", "thuốc mỡ" }));

        dgvXuatThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "ID", "Ng.Bán", "Tên KH", "Tên Thuốc", "Loại Thuốc", "Đơn Gía", "Số lượng", "Ngày Xuất", "Thành Tiền"
            }
        ));
        dgvXuatThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dgvXuatThuocMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dgvXuatThuoc);

        jLabel10.setText("Tên KH");

        jLabel11.setText("Đơn Giá");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnQuayLai)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel11))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_NguoiBan, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_TenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txt_NgayXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbxLoaiThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(363, 363, 363))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btnThem)
                        .addGap(128, 128, 128)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(164, 164, 164)
                                .addComponent(btnLamMoi)
                                .addContainerGap(295, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnTimKiem)
                                .addGap(192, 192, 192))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnQuayLai))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_NguoiBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxLoaiThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txt_NgayXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_TenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTimKiem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnXoa)
                            .addComponent(btnSua)
                            .addComponent(btnLamMoi))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
       int xacNhan = JOptionPane.showConfirmDialog(null,"Bạn có muốn xóa không",null,JOptionPane.YES_NO_OPTION);
        if(xacNhan == JOptionPane.YES_OPTION){
            
            
             XuatThuoc thuoc = new XuatThuoc();
             int ID = (Integer) model.getValueAt(dgvXuatThuoc.getSelectedRow(), 1);  
                 thuoc.setID(ID);
                 
              if(new DAO().xoaXuatThuoc(thuoc)){
                     JOptionPane.showMessageDialog(rootPane,"Xóa Thành Công");
             
                     Clear();
                     model.removeRow(dgvXuatThuoc.getSelectedRow());
                     btnThem.setEnabled(true);
            
                 }
                 else{
                     JOptionPane.showMessageDialog(rootPane,"Xóa thất bại !");
                }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        new ManHinhChinh().setVisible(true);
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if(txt_TenThuoc.getText().equals("") || txt_NguoiBan.getText().equals("") || txt_NgayXuat.getText().equals("") || cbxLoaiThuoc.getSelectedItem().toString().equals("") || txt_DonGia.getText().equals("") || spnSoLuong.getValue().equals("") ){
                   
                   JOptionPane.showMessageDialog(rootPane,"Vui lòng nhập đầy đủ thông tin !");
                   
                  
               }
               else{
            
                  if(!txt_NgayXuat.getText().contains("/")){
                        JOptionPane.showMessageDialog(rootPane,"Đinh dạng ngày không hợp lệ !");
                   }
                  else{
                       XuatThuoc xuatthuoc = new XuatThuoc();
                 
                 xuatthuoc.setNguoiBan(txt_NguoiBan.getText());
                 xuatthuoc.setNgayXuat(txt_NgayXuat.getText());
                 xuatthuoc.setTenKH(txt_TenKH.getText());
                 xuatthuoc.setTenThuoc(txt_TenThuoc.getText());
                 xuatthuoc.setLoaiThuoc(cbxLoaiThuoc.getSelectedItem().toString());
                 xuatthuoc.setDonGia(Integer.parseInt(txt_DonGia.getText()));
                 int value = (Integer) spnSoLuong.getValue();
                 xuatthuoc.setSoLuong(value);
                 xuatthuoc.setDonGia(Integer.parseInt(txt_DonGia.getText()));
                 
                 int thanhtien = value * Integer.parseInt(txt_DonGia.getText());
                 txtThanhTien.setText(String.valueOf(thanhtien));
                 xuatthuoc.setThanhTien(thanhtien);
              
                 if(new DAO().xuatThuoc(xuatthuoc)){
                     JOptionPane.showMessageDialog(rootPane,"Thêm Thành Công");
                     list.add(xuatthuoc);
                     
                     
                      HoaDonXuat hdx = new HoaDonXuat();
                 
                 hdx.setNguoiBan(txt_NguoiBan.getText());
                 hdx.setNgayXuat(txt_NgayXuat.getText());
                 hdx.setTenKH(txt_TenKH.getText());
                 hdx.setTenThuoc(txt_TenThuoc.getText());
                 hdx.setLoaiThuoc(cbxLoaiThuoc.getSelectedItem().toString());
                 hdx.setDonGia(Integer.parseInt(txt_DonGia.getText()));
                 int value1 = (Integer) spnSoLuong.getValue();
                 hdx.setSoLuong(value1);
                 hdx.setDonGia(Integer.parseInt(txt_DonGia.getText()));
                 
                 int thanhtien1 = value * Integer.parseInt(txt_DonGia.getText());
                 txtThanhTien.setText(String.valueOf(thanhtien1));
                 xuatthuoc.setThanhTien(thanhtien);
                         DAO dao = new DAO();
                    dao.themHoaDonXuat(hdx);
                 }
                 else{
                     JOptionPane.showMessageDialog(rootPane,"Thêm thất bại !");
                 }
                 Clear();
                 HienThi();   
             }          
        }     
    }//GEN-LAST:event_btnThemActionPerformed

    private void dgvXuatThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dgvXuatThuocMouseClicked
      
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);
        btnThem.setEnabled(false);
        
        txt_NguoiBan.setText(model.getValueAt(dgvXuatThuoc.getSelectedRow(), 2).toString());
        txt_TenKH.setText(model.getValueAt(dgvXuatThuoc.getSelectedRow(), 3).toString());
        txt_TenThuoc.setText(model.getValueAt(dgvXuatThuoc.getSelectedRow(), 4).toString());
        cbxLoaiThuoc.setSelectedItem(model.getValueAt(dgvXuatThuoc.getSelectedRow(), 5).toString());
        txt_DonGia.setText(model.getValueAt(dgvXuatThuoc.getSelectedRow(), 6).toString());
        spnSoLuong.setValue(model.getValueAt(dgvXuatThuoc.getSelectedRow(), 7));
        txt_NgayXuat.setText(model.getValueAt(dgvXuatThuoc.getSelectedRow(), 8).toString());
        txtThanhTien.setText(model.getValueAt(dgvXuatThuoc.getSelectedRow(), 9).toString());
    }//GEN-LAST:event_dgvXuatThuocMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
         if (dgvXuatThuoc.getSelectedRow()==-1) {
            if (dgvXuatThuoc.getRowCount()==0) {
                  JOptionPane.showMessageDialog(rootPane,"Bảng Trống !");
            }
            else{
                  JOptionPane.showMessageDialog(rootPane,"Vui lòng chọn Thuốc !");
            }
        }
         else{
                    XuatThuoc xuatthuoc = new XuatThuoc();
                 int ID = (Integer) model.getValueAt(dgvXuatThuoc.getSelectedRow(), 1);  
                 xuatthuoc.setID(ID);
                 xuatthuoc.setNguoiBan(txt_NguoiBan.getText());
                 xuatthuoc.setNgayXuat(txt_NgayXuat.getText());
                 xuatthuoc.setTenKH(txt_TenKH.getText());
                 xuatthuoc.setTenThuoc(txt_TenThuoc.getText());
                 xuatthuoc.setLoaiThuoc(cbxLoaiThuoc.getSelectedItem().toString());
                 xuatthuoc.setDonGia(Integer.parseInt(txt_DonGia.getText()));
                 int value = (Integer) spnSoLuong.getValue();
                 xuatthuoc.setSoLuong(value);
                 xuatthuoc.setDonGia(Integer.parseInt(txt_DonGia.getText()));
                 xuatthuoc.setThanhTien(Integer.parseInt(txtThanhTien.getText()));
                 
                if(new DAO().suaXuatThuoc(xuatthuoc)){
                     JOptionPane.showMessageDialog(rootPane,"Sửa Thành Công");
                     list.add(xuatthuoc);
                   
                 }
                else{
                    JOptionPane.showMessageDialog(rootPane,"Sửa thất bại !");
                }
             
            DefaultTableModel model = (DefaultTableModel) dgvXuatThuoc.getModel();
             
            model.setValueAt(txt_NguoiBan.getText(),dgvXuatThuoc.getSelectedRow(), 2);
            model.setValueAt(txt_TenKH.getText(), dgvXuatThuoc.getSelectedRow(), 3);
            model.setValueAt(txt_TenThuoc.getText(), dgvXuatThuoc.getSelectedRow(), 4);
            model.setValueAt(cbxLoaiThuoc.getSelectedItem().toString(), dgvXuatThuoc.getSelectedRow(), 5);
            model.setValueAt(txt_DonGia.getText(), dgvXuatThuoc.getSelectedRow(), 6);
            model.setValueAt(spnSoLuong.getValue(), dgvXuatThuoc.getSelectedRow(), 7);
            model.setValueAt(txt_NgayXuat.getText(), dgvXuatThuoc.getSelectedRow(), 8);
            model.setValueAt(txtThanhTien.getText(), dgvXuatThuoc.getSelectedRow(), 9);
           
             btnSua.setEnabled(false);
             btnXoa.setEnabled(true);
             btnThem.setEnabled(true);
              
             txt_NguoiBan.setText("");
             txt_NgayXuat.setText("");
             txt_TenThuoc.setText("");
             txt_DonGia.setText("");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
       Clear();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
         boolean isKetQua = true;
         
         Vector  row = new Vector();
         int STT =1; 
            while(model.getRowCount() >0)
              {
                  model.removeRow(0);
              }
             
             
             ArrayList<XuatThuoc> listTimKiem; 
                     
              listTimKiem =new DAO().searchXuatThuoc(txtTimKiem.getText().toString());
              isKetQua = false;
              if(txtTimKiem.getText().equals("")){
               HienThi();
             }
         
              if(isKetQua == false){
                        
                  
                    for (XuatThuoc xt : listTimKiem) {
                        
                        row.add(STT);
                        row.add(xt.getID());
                        row.add(xt.getNguoiBan());
                        row.add(xt.getTenKH());
                        row.add(xt.getTenThuoc());
                        row.add(xt.getLoaiThuoc());
                        row.add(xt.getDonGia());
                        row.add(xt.getSoLuong());
                        row.add(xt.getNgayXuat());
                        row.add(xt.getThanhTien());
                        model.addRow(row);
                    }
                    STT ++;
                    model.fireTableDataChanged();
                }
              else{
                     row.add(STT);
                        row.add("");
                        row.add("");
                        row.add("");
                        row.add("");
                        row.add("");
                        row.add("");
                        row.add("");
                        row.add("");
                        row.add("");
                        model.fireTableDataChanged();
              }
              
        
    }//GEN-LAST:event_btnTimKiemActionPerformed
        private void Clear(){
           txt_NguoiBan.setText("");
          txt_NgayXuat.setText("");
          txt_TenKH.setText("");
          txt_TenThuoc.setText("");
           txt_DonGia.setText("");
    }
    public void HienThi(){
         model.setRowCount(0);
        int STT =1;
        for (XuatThuoc t : list) {
          
            model.addRow(new Object[]{STT,t.getID(),
             t.getNguoiBan(),t.getTenKH(),t.getTenThuoc(),t.getLoaiThuoc(),t.getDonGia(),t.getSoLuong(),t.getNgayXuat(),t.getThanhTien()
            });
            STT ++;
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyXuatThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyXuatThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyXuatThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyXuatThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyXuatThuoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox cbxLoaiThuoc;
    private javax.swing.JTable dgvXuatThuoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner spnSoLuong;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txt_DonGia;
    private javax.swing.JTextField txt_NgayXuat;
    private javax.swing.JTextField txt_NguoiBan;
    private javax.swing.JTextField txt_TenKH;
    private javax.swing.JTextField txt_TenThuoc;
    // End of variables declaration//GEN-END:variables
}
