/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package doan;

import java.awt.List;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class QuanLyNhapThuoc extends javax.swing.JFrame {

    
    
    private ArrayList<Thuoc> list;
    DefaultTableModel model;
    /**
     * Creates new form QuanLyNhapThuoc
     */
    public QuanLyNhapThuoc() {
        initComponents();
        list = new DAO().getListThuoc();
        model =(DefaultTableModel) dgvThuoc.getModel();
        HienThi();
        btnSua.setEnabled(false);
        btnSua.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        txt_TimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        spnSoLuong = new javax.swing.JSpinner();
        txt_MaThuoc = new javax.swing.JTextField();
        txt_TenThuoc = new javax.swing.JTextField();
        txt_DonGia = new javax.swing.JTextField();
        txt_NguoiNhap = new javax.swing.JTextField();
        cbxLoaiThuoc = new javax.swing.JComboBox();
        txt_NgayNhap = new javax.swing.JTextField();
        txt_HSD = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        dgvThuoc = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\java\\DoAn\\src\\Image\\iconfinder_586_Medicine_pills_tablets_4212198.png")); // NOI18N
        jLabel1.setText("QUẢN LÝ NHẬP THUỐC");

        jLabel2.setText("Mã Thuốc");

        jLabel3.setText("Tên Thuốc");

        jLabel4.setText("Loại Thuốc");

        jLabel5.setText("Số Lượng");

        jLabel6.setText("Đơn Gía");

        jLabel7.setText("Người Nhập");

        jLabel8.setText("Ngày Nhập");

        jLabel9.setText("Hạn Sử Dụng");

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconfinder_199_CircledPlus_183316.png"))); // NOI18N
        btnThem.setText("Thêm ");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconfinder_basket_1814090.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconfinder_Setting01_928428.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconfinder_back3_216570.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconfinder_11_Search_106236.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconfinder_left_3_4829864.png"))); // NOI18N
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        cbxLoaiThuoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kháng Sinh", "Vỉtamin", "Thuốc giảm đau", "Thuốc giảm cân", "Thuốc cảm cúm", "Thuốc đau họng", "thuốc mỡ", " " }));

        dgvThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Ng.Nhập", "Mã Thuốc", "Tên Thuốc", "Loại Thuốc", "Đơn Gía", "Số lượng", "Ngày Nhập", "HSD"
            }
        ));
        dgvThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dgvThuocMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dgvThuoc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnQuayLai)
                                .addGap(164, 164, 164))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel5))
                                .addGap(11, 11, 11)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_TenThuoc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                        .addComponent(txt_MaThuoc, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(cbxLoaiThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(191, 191, 191)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(83, 83, 83)
                                            .addComponent(txt_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_NguoiNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_NgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_HSD, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(jLabel1)))
                        .addGap(351, 351, 351))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnTimKiem)
                .addGap(84, 84, 84))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(btnThem)
                .addGap(150, 150, 150)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnQuayLai))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(txt_MaThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_TenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NguoiNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxLoaiThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_NgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spnSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_HSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnLamMoi))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem)
                    .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int xacNhan = JOptionPane.showConfirmDialog(null,"Bạn có muốn xóa không",null,JOptionPane.YES_NO_OPTION);
        if(xacNhan == JOptionPane.YES_OPTION){
            
            
             Thuoc thuoc = new Thuoc();
             thuoc.setMaThuoc(txt_MaThuoc.getText()); 
                 
              if(new DAO().xoaThuoc(thuoc)){
                     JOptionPane.showMessageDialog(rootPane,"Xóa Thành Công");
             
                     Clear();
                     model.removeRow(dgvThuoc.getSelectedRow());
                     btnThem.setEnabled(true);
                     txt_MaThuoc.setEnabled(true);
                 }
                 else{
                     JOptionPane.showMessageDialog(rootPane,"Xóa thất bại !");
                }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
          new ManHinhChinh().setVisible(true);
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
               if(txt_NguoiNhap.getText().equals("") || txt_NguoiNhap.getText().equals("") || txt_NgayNhap.getText().equals("") || txt_HSD.getText().equals("") || txt_TenThuoc.getText().equals("") || cbxLoaiThuoc.getSelectedItem().toString().equals("") || txt_DonGia.getText().equals("") || spnSoLuong.getValue().equals("")){
                   
                   JOptionPane.showMessageDialog(rootPane,"Vui lòng nhập đầy đủ thông tin !");
                   
               }
               else{
                   if(!txt_NgayNhap.getText().contains("/") || !txt_HSD.getText().contains("/") ){
                        JOptionPane.showMessageDialog(rootPane,"Đinh dạng ngày không hợp lệ !");
                   }
                   else{
                         Thuoc thuoc = new Thuoc();
                 thuoc.setMaThuoc(txt_NguoiNhap.getText());
                 thuoc.setNguoiNhap(txt_MaThuoc.getText());
                 thuoc.setNgayNhap(txt_NgayNhap.getText());
                 thuoc.setHSD(txt_HSD.getText());
                 thuoc.setTenThuoc(txt_TenThuoc.getText());
                 thuoc.setLoaiThuoc(cbxLoaiThuoc.getSelectedItem().toString());
                 thuoc.setDonGia(Integer.parseInt(txt_DonGia.getText()));
                 int value = (Integer) spnSoLuong.getValue();
                 thuoc.setSoLuong(value);
                 
              
                 if(new DAO().themThuoc(thuoc)){
                     JOptionPane.showMessageDialog(rootPane,"Thêm Thành Công");
                     list.add(thuoc);
                     
                     DAO dao = new DAO();
                     
                     
                     HoaDonNhap hdn = new HoaDonNhap();
                     
                 hdn.setMaThuoc(txt_NguoiNhap.getText());
                 hdn.setNguoiNhap(txt_MaThuoc.getText());
                 hdn.setNgayNhap(txt_NgayNhap.getText());
                 hdn.setHSD(txt_HSD.getText());
                 hdn.setTenThuoc(txt_TenThuoc.getText());
                 hdn.setLoaiThuoc(cbxLoaiThuoc.getSelectedItem().toString());
                 hdn.setDonGia(Integer.parseInt(txt_DonGia.getText()));
                 int value1 = (Integer) spnSoLuong.getValue();
                 hdn.setSoLuong(value1);
                     dao.themHoaDonNhap(hdn);
                 }
                 else{
                     JOptionPane.showMessageDialog(rootPane,"Thêm thất bại !");
                 }
                 Clear();                
                HienThi();
                   }
               }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
         Clear();
          
    }//GEN-LAST:event_btnLamMoiActionPerformed
    
    private void Clear(){
           txt_NguoiNhap.setText("");
          txt_MaThuoc.setText("");
          txt_NgayNhap.setText("");
          txt_NgayNhap.setText("");
          txt_HSD.setText("");
          txt_TenThuoc.setText("");
           txt_DonGia.setText("");
    }
    private void dgvThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dgvThuocMouseClicked
        // TODO add your handling code here:
        
         
        
        txt_MaThuoc.setEnabled(false);
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);
        btnThem.setEnabled(false);
        
        txt_NguoiNhap.setText(model.getValueAt(dgvThuoc.getSelectedRow(), 1).toString());
        txt_MaThuoc.setText(model.getValueAt(dgvThuoc.getSelectedRow(), 2).toString());
        txt_TenThuoc.setText(model.getValueAt(dgvThuoc.getSelectedRow(), 3).toString());
        cbxLoaiThuoc.setSelectedItem(model.getValueAt(dgvThuoc.getSelectedRow(), 4).toString());
        txt_DonGia.setText(model.getValueAt(dgvThuoc.getSelectedRow(), 5).toString());
        spnSoLuong.setValue(model.getValueAt(dgvThuoc.getSelectedRow(), 6));
        txt_NgayNhap.setText(model.getValueAt(dgvThuoc.getSelectedRow(), 7).toString());
        txt_HSD.setText(model.getValueAt(dgvThuoc.getSelectedRow(), 8).toString());
    }//GEN-LAST:event_dgvThuocMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
          
         if (dgvThuoc.getSelectedRow()==-1) {
            if (dgvThuoc.getRowCount()==0) {
                  JOptionPane.showMessageDialog(rootPane,"Bảng Trống !");
            }
            else{
                  JOptionPane.showMessageDialog(rootPane,"Vui lòng chọn Thuốc !");
            }
        }
         else{
                 Thuoc thuoc = new Thuoc();
                 
                 thuoc.setMaThuoc(txt_MaThuoc.getText());
                 thuoc.setNguoiNhap(txt_NguoiNhap.getText());
                 thuoc.setNgayNhap(txt_NgayNhap.getText());
                 thuoc.setHSD(txt_HSD.getText());
                 thuoc.setTenThuoc(txt_TenThuoc.getText());
                 thuoc.setLoaiThuoc(cbxLoaiThuoc.getSelectedItem().toString());
                 thuoc.setDonGia(Integer.parseInt(txt_DonGia.getText()));
                 int value = (Integer) spnSoLuong.getValue();
                 thuoc.setSoLuong(value);
                 
                if(new DAO().suaThuoc(thuoc)){
                     JOptionPane.showMessageDialog(rootPane,"Sửa Thành Công");
                     list.add(thuoc);
        
                 }
                else{
                    JOptionPane.showMessageDialog(rootPane,"Sửa thất bại !");
                }
             
            DefaultTableModel model = (DefaultTableModel) dgvThuoc.getModel();
            model.setValueAt(txt_NguoiNhap.getText(),dgvThuoc.getSelectedRow(), 1);
            model.setValueAt(txt_MaThuoc.getText().toString(), dgvThuoc.getSelectedRow(), 2);
            model.setValueAt(txt_TenThuoc.getText(), dgvThuoc.getSelectedRow(), 3);
             model.setValueAt(cbxLoaiThuoc.getSelectedItem().toString(), dgvThuoc.getSelectedRow(), 4);
            model.setValueAt(txt_DonGia.getText(), dgvThuoc.getSelectedRow(), 5);
            model.setValueAt(spnSoLuong.getValue(), dgvThuoc.getSelectedRow(), 6);
            model.setValueAt(txt_NgayNhap.getText(), dgvThuoc.getSelectedRow(), 7);
            model.setValueAt(txt_HSD.getText(), dgvThuoc.getSelectedRow(), 8);
           
             btnSua.setEnabled(false);
             btnXoa.setEnabled(true);
             txt_MaThuoc.setEnabled(true);
             btnThem.setEnabled(true);
              
             txt_NguoiNhap.setText("");
             txt_MaThuoc.setText("");
             txt_NgayNhap.setText("");
             txt_NgayNhap.setText("");
             txt_HSD.setText("");
             txt_TenThuoc.setText("");
             txt_DonGia.setText("");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        
        boolean isKetQua = true;     
        Vector  row = new Vector();
        int STT =1; 
        
            while(model.getRowCount() >0)
              {
                  model.removeRow(0);
              }
               ArrayList<Thuoc> listTimKiem; 
                     
              listTimKiem =new DAO().searchThuoc(txt_TimKiem.getText().toString());
              isKetQua = false;
              
              if(txt_TimKiem.getText().equals("")){
                  HienThi();
              }
              if(isKetQua == false){
                       
                        for (Thuoc thuoc : listTimKiem) {
                                row.add(STT);
                                row.add(thuoc.getNguoiNhap());
                                row.add(thuoc.getMaThuoc());
                                row.add(thuoc.getTenThuoc());
                                row.add(thuoc.getLoaiThuoc());
                                row.add(thuoc.getDonGia());
                                row.add(thuoc.getSoLuong());
                                row.add(thuoc.getNgayNhap());
                                row.add(thuoc.getHSD());
                                model.addRow(row);
                        }
                        STT ++;
                        model.fireTableDataChanged();    
              }
              else{
                       row.add(STT);
                                row.add("");
                                row.add("");
                                row.add("");
                                row.add("");
                                row.add("");
                                row.add("");
                                row.add("");
                                row.add("");
                                model.addRow(row);
                                model.fireTableDataChanged(); 
             }
       
       
    }//GEN-LAST:event_btnTimKiemActionPerformed
    public void HienThi(){
         model.setRowCount(0);
        int STT =1;
        for (Thuoc t : list) {
          
            model.addRow(new Object[]{STT,
             t.getNguoiNhap(),t.getMaThuoc(),t.getTenThuoc(),t.getLoaiThuoc(),t.getDonGia(),t.getSoLuong(),t.getNgayNhap(),t.getHSD()
            });
            STT ++;
        }
        
    }
    
    
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhapThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhapThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhapThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhapThuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhapThuoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox cbxLoaiThuoc;
    private javax.swing.JTable dgvThuoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner spnSoLuong;
    private javax.swing.JTextField txt_DonGia;
    private javax.swing.JTextField txt_HSD;
    private javax.swing.JTextField txt_MaThuoc;
    private javax.swing.JTextField txt_NgayNhap;
    private javax.swing.JTextField txt_NguoiNhap;
    private javax.swing.JTextField txt_TenThuoc;
    private javax.swing.JTextField txt_TimKiem;
    // End of variables declaration//GEN-END:variables

    static class setVisible {

        public setVisible(boolean b) {
        }
    }
}
